import {
  Button,
  Input,
  Modal,
  ModalBody,
  ModalContent,
  ModalFooter,
  ModalHeader,
  Select,
  SelectItem,
  Switch,
} from "@heroui/react";
import { useFormik } from "formik";
import { useEffect } from "react";
import * as Yup from "yup";
import { EVENTS, SOURCES } from "../../../consts/integrations";

interface AddWebhookModalProps {
  isOpen: boolean;
  onClose: () => void;
  onSave: (webhook: WebhookConfig) => void;
  editingWebhook?: WebhookConfig | null;
}

export interface WebhookConfig {
  id?: string;
  name: string;
  url?: string; // Generated by API
  source: string;
  events: string[];
  isActive: boolean;
}

const webhookSchema = Yup.object().shape({
  name: Yup.string()
    .required("Webhook name is required")
    .min(3, "Name must be at least 3 characters"),
  source: Yup.string().required("Source is required"),
  events: Yup.array()
    .of(Yup.string())
    .min(1, "At least one event must be selected")
    .required("Events are required"),
  isActive: Yup.boolean(),
});

export default function AddWebhookModal({
  isOpen,
  onClose,
  onSave,
  editingWebhook,
}: AddWebhookModalProps) {
  const formik = useFormik({
    initialValues: {
      name: editingWebhook?.name || "",
      source: editingWebhook?.source || "",
      events: editingWebhook?.events || [],
      isActive: editingWebhook?.isActive ?? true,
    },
    validationSchema: webhookSchema,
    onSubmit: (values) => {
      const webhook: WebhookConfig = {
        id: editingWebhook?.id || Date.now().toString(),
        ...values,
      };
      onSave(webhook);
      handleClose();
    },
    enableReinitialize: true,
  });

  useEffect(() => {
    if (isOpen && editingWebhook) {
      formik.setValues({
        name: editingWebhook.name,
        source: editingWebhook.source,
        events: editingWebhook.events,
        isActive: editingWebhook.isActive,
      });
    } else if (isOpen && !editingWebhook) {
      formik.resetForm();
    }
  }, [isOpen, editingWebhook]);

  const handleClose = () => {
    formik.resetForm();
    onClose();
  };

  return (
    <Modal isOpen={isOpen} onClose={handleClose} size="lg">
      <ModalContent>
        <form onSubmit={formik.handleSubmit}>
          <ModalHeader className="flex flex-col gap-1 p-4">
            <h4 className="text-base font-medium">
              {editingWebhook ? "Edit Webhook" : "Add New Webhook"}
            </h4>
            <p className="text-xs text-gray-500 font-normal">
              Configure webhook to receive real-time event notifications
            </p>
          </ModalHeader>
          <ModalBody className="px-4 py-0 gap-4">
            {/* Webhook Name */}
            <Input
              size="sm"
              radius="sm"
              label="Webhook Name"
              labelPlacement="outside"
              placeholder="e.g., New Referral Webhook"
              name="name"
              value={formik.values.name}
              onChange={formik.handleChange}
              onBlur={formik.handleBlur}
              isRequired
              {...(formik.touched.name &&
                formik.errors.name && {
                  isInvalid: true,
                  errorMessage: formik.errors.name,
                })}
            />

            {/* Source Select (Single) */}
            <Select
              size="sm"
              radius="sm"
              label="Source"
              labelPlacement="outside"
              placeholder="Select a source"
              selectedKeys={formik.values.source ? [formik.values.source] : []}
              disabledKeys={formik.values.source ? [formik.values.source] : []}
              onSelectionChange={(keys) => {
                const selected = Array.from(keys)[0] as string;
                formik.setFieldValue("source", selected);
              }}
              isRequired
              {...(formik.touched.source &&
                formik.errors.source && {
                  isInvalid: true,
                  errorMessage: formik.errors.source,
                })}
            >
              {SOURCES.map((source) => (
                <SelectItem key={source.value}>{source.label}</SelectItem>
              ))}
            </Select>

            {/* Events Select (Multiple) */}
            <Select
              size="sm"
              radius="sm"
              label="Events"
              labelPlacement="outside"
              placeholder="Select events"
              selectionMode="multiple"
              selectedKeys={new Set(formik.values.events)}
              onSelectionChange={(keys) => {
                const selected = Array.from(keys) as string[];
                formik.setFieldValue("events", selected);
              }}
              isRequired
              {...(formik.touched.events &&
                typeof formik.errors.events === "string" && {
                  isInvalid: true,
                  errorMessage: formik.errors.events,
                })}
            >
              {EVENTS.map((event) => (
                <SelectItem key={event.value}>{event.label}</SelectItem>
              ))}
            </Select>

            {/* Active Status Switch */}
            <div className="flex items-center justify-between p-3 bg-gray-50 rounded-lg">
              <div className="space-y-1">
                <p className="text-sm font-medium">Active Status</p>
                <p className="text-xs text-gray-500">
                  Enable or disable this webhook
                </p>
              </div>
              <Switch
                size="sm"
                isSelected={formik.values.isActive}
                onValueChange={(value) =>
                  formik.setFieldValue("isActive", value)
                }
                color="primary"
              />
            </div>
          </ModalBody>
          <ModalFooter className="p-4">
            <Button
              size="sm"
              radius="sm"
              variant="ghost"
              className="border-small"
              onPress={handleClose}
              type="button"
            >
              Cancel
            </Button>
            <Button
              size="sm"
              radius="sm"
              color="primary"
              type="submit"
              isDisabled={!formik.isValid || formik.isSubmitting}
            >
              {editingWebhook ? "Update Webhook" : "Add Webhook"}
            </Button>
          </ModalFooter>
        </form>
      </ModalContent>
    </Modal>
  );
}
